spring:
  application:
    name: jerseyverse-backend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/jerseyverse_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:jainish}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: ${HIBERNATE_BIND_LOG_LEVEL:TRACE}

jwt:
  secret: ${JWT_SECRET:8vP7mX2kN5qL9rT4yH1cJ6wE3uF8aB2zK7nM5pQ9sR4tY6vX1cD8eF3gH7jL2mN}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  upload:
    product-dir: ${PRODUCT_UPLOAD_DIR:uploads/products}

  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:ztoxffzd}
  api-key: ${CLOUDINARY_API_KEY:614838683452116}
  api-secret: ${CLOUDINARY_API_SECRET:UboVwPJFQpxp2dx-Bn2QSXBnGsU}

server:
  port: ${PORT:8081}