spring:
  application:
    name: jerseyverse-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/jerseyverse_db
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD

  jpa:
    hibernate:
      ddl-auto: update   # Options: none, validate, update, create, create-drop
    show-sql: true       # Logs SQL queries in console
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE

jwt:
    secret: YOUR_JWT_SECRET
    expiration: 86400000

app:
  upload:
    product-dir: uploads/products

server:
  port: 8081